pool:
  vmImage: vs2017-win2016

steps:
- task: AzurePowerShell@5
  displayName: 'Build Module'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: psake.ps1
    azurePowerShellVersion: LatestVersion

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: PSDB

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Build'
  inputs:
    ArtifactName: Build

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/Tests/results/test-results.xml'
